"""empty message

Revision ID: a8462980c76f
Revises: e94bd1b983fe
Create Date: 2023-10-03 15:08:54.513955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8462980c76f'
down_revision = 'e94bd1b983fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('moviename', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('collects',
    sa.Column('userid', sa.Integer(), nullable=False),
    sa.Column('movieid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['movieid'], ['movie.id'], ),
    sa.ForeignKeyConstraint(['userid'], ['user.id'], ),
    sa.PrimaryKeyConstraint('userid', 'movieid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('collects')
    op.drop_table('user')
    op.drop_table('movie')
    # ### end Alembic commands ###
